version: "3.8"

services:
  backend:
    build: ./backend-docker-info-api
    container_name: backend

  project1:
    build: ./project1-csc424-home
    container_name: project1

  project2:
    build: ./project2-docker-info
    container_name: project2

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - project1
      - project2
